### ISSUE TITLE
Using C library fails to compile with 2.2.0 but works with 2.1.0

### ISSUE THREAD

**Issue by horgh** [dmlc/treelite#345]
Compiling using 2.2.0 gives me this error:

```
In file included from ./local/include/treelite/c_api.h:15,
                 from mm-xgboost-codegen.c:8:
./local/include/treelite/c_api_common.h:54:8: error: expected identifier or ‘(’ before string constant                                                                 
   54 | extern "C" {
      |        ^~~
```

From a look at the changes in 2.2.0, I think the issue is here: https://github.com/dmlc/treelite/blob/1f9c5054ad7433fa88623fccf0ae46a6ba6a27c6/include/treelite/c_api_common.h#L54 from https://github.com/dmlc/treelite/pull/325.

I think instead of `extern "C"` we'd want to use the macro `TREELITE_EXTERN_C`. Or maybe `TREELITE_DLL`, I'm not sure.

Thank you!

**Comment by hcho3** [comment]
Can you provide more details in your environment? There isn't a source file named mm-xgboost-codegen.c in Treelite.

**Comment by hcho3** [comment]
Ah, you are using the header from a C translation unit. You are right, `extern "C"` should be replaced with `TREELITE_EXTERN_C`. Let me fix that.

**Comment by horgh** [comment]
`mm-xgboost-code.c` is a standalone program using the treelite C API like so:

```c
#include <treelite/c_api.h>
```

Using functions such as `TreeliteLoadXGBoostModel()`.

**Comment by hcho3** [comment]
Just opened #348 to fix the issue.

**Comment by horgh** [comment]
Thank you!
