### ISSUE TITLE
can not build on mac os Catalina (10.15.5 (19F101))

### ISSUE THREAD

**Issue by giftal** [dmlc/treelite#184]
Undefined symbols for architecture x86_64:
  "treelite::frontend::LoadProtobufModel(char const*, treelite::Model*)", referenced from:
      _TreeliteLoadProtobufModel in c_api.cc.o
ld: symbol(s) not found for architecture x86_64

**Comment by hcho3** [comment]
Should be fixed in #185

**Comment by giftal** [comment]
Works now!
